name: al_fatawa_library
description: A simple Islamic library for Al Furqan Scholars Academy.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/books.json
    - assets/logo.png
